name: Lighthouse

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          cache: pnpm
          node-version: 24

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build application
        run: pnpm build

      - name: Run Lighthouse CI
        run: pnpm lighthouse

      - name: Upload Lighthouse artifacts
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: lighthouse-report
          path: .lighthouseci
